"""
Prometheus Metrics Exposition Endpoint for Error Triage Service

This module implements the /metrics endpoint for Prometheus-compatible metrics exposition
per Section 0.1.1 (Operational Excellence) and Section 6.5.3 (Monitoring and Observability).

The endpoint exposes all application counters and histograms in Prometheus text exposition
format (version 0.0.4) for scraping by Prometheus server or CloudWatch Agent with
Prometheus integration enabled.

Metrics Exposed:
- events_received_total: Total webhook events received from Vercel and GCP
- events_processed_total: Successfully processed events after fingerprinting
- events_deduplicated_total: Duplicate events dropped via idempotency cache
- jira_issues_created_total: New Jira Bug issues created for novel error fingerprints
- jira_comments_added_total: Comments added to existing issues for repeated errors
- jira_escalations_total: Issues with escalated priority due to threshold crossings
- errors_total: Application errors by type for monitoring and alerting
- event_processing_duration_seconds: Webhook processing latency histogram
- jira_api_latency_seconds: Jira API operation duration histogram
- redis_operation_latency_seconds: Redis operation duration histogram

Security:
- No authentication required per Section 6.5.3.2 (internal VPC access only)
- Security groups restrict access to monitoring infrastructure
- Never exposes internal error details to metrics scraper

Prometheus Scrape Configuration Example:
    scrape_configs:
      - job_name: 'error-triage'
        static_configs:
          - targets: ['error-triage.internal:8080']
        metrics_path: '/metrics'
        scrape_interval: 15s
        scrape_timeout: 10s

CloudWatch Agent Configuration Example:
    {
      "logs": {
        "metrics_collected": {
          "prometheus": {
            "prometheus_config_path": "/etc/prometheus.yml",
            "emf_processor": {
              "metric_namespace": "Jiratest/ErrorTriage",
              "metric_declaration": [
                {
                  "source_labels": ["job"],
                  "label_matcher": "error-triage",
                  "dimensions": [["environment", "source"]],
                  "metric_selectors": ["^events_.*"]
                }
              ]
            }
          }
        }
      }
    }

Technical References:
- Section 0.1.1: Operational Excellence requirements
- Section 0.4.4: CloudWatch Metrics Published catalog
- Section 0.5.1: Group 7 - Operational Endpoints implementation plan
- Section 6.5.3: Monitoring and Observability architecture

Author: Blitzy Platform
Version: 1.0.0
"""

from typing import Tuple

from flask import Blueprint, Response

from src.utils.logging_config import get_logger
from src.utils.metrics_collector import MetricsCollector

# Initialize module logger for structured JSON logging
logger = get_logger(__name__)

# Create Flask Blueprint for metrics endpoint
# No URL prefix - endpoint available at /metrics from application root
metrics_bp = Blueprint("metrics", __name__)


@metrics_bp.route("/metrics", methods=["GET"])
def handle_metrics() -> Tuple[Response, int] | Tuple[str, int, dict]:
    """
    Handle GET /metrics requests for Prometheus metrics exposition.

    Returns all registered Prometheus metrics (counters and histograms) in
    text exposition format per Prometheus specification version 0.0.4.
    Metrics are automatically collected from all application components via
    the MetricsCollector singleton instance.

    The response includes TYPE and HELP comments for each metric, followed by
    metric values with labels. Histograms include bucket counts, sum, and count
    automatically generated by prometheus_client library.

    Example Response Format:
        # HELP events_received_total Total webhook events received
        # TYPE events_received_total counter
        events_received_total{environment="production",source="vercel"} 1234.0
        events_received_total{environment="production",source="gcp"} 567.0

        # HELP event_processing_duration_seconds Webhook processing latency in seconds
        # TYPE event_processing_duration_seconds histogram
        event_processing_duration_seconds_bucket{le="0.01",environment="production",source="vercel"} 100.0
        event_processing_duration_seconds_bucket{le="0.05",environment="production",source="vercel"} 450.0
        event_processing_duration_seconds_bucket{le="0.1",environment="production",source="vercel"} 890.0
        event_processing_duration_seconds_bucket{le="+Inf",environment="production",source="vercel"} 1234.0
        event_processing_duration_seconds_sum{environment="production",source="vercel"} 85.234
        event_processing_duration_seconds_count{environment="production",source="vercel"} 1234.0

    Returns:
        Tuple containing:
        - Response body: Prometheus text exposition format metrics
        - HTTP status code: 200 OK on success, 500 Internal Server Error on failure
        - Headers: Content-Type set to 'text/plain; version=0.0.4; charset=utf-8'

    Error Handling:
        On any exception during metric generation:
        - Logs error with action='metrics_endpoint_error' and error_type
        - Returns 500 status with generic error message
        - Never exposes internal error details to scraper per Section 6.5.3.2

    Security:
        - No authentication required (internal VPC access only)
        - Access restricted by security groups to monitoring infrastructure
        - Error messages sanitized to prevent information disclosure

    Performance:
        - Typical response time: < 50ms for ~20 metrics with multiple label combinations
        - No database queries or external API calls
        - Metrics stored in memory for fast serialization
        - Suitable for 15-second scrape intervals (Prometheus default)

    Multi-Process Support:
        When PROMETHEUS_MULTIPROC_DIR environment variable is set (Gunicorn workers):
        - Metrics automatically aggregated across all worker processes
        - Counter values summed from all workers
        - Histogram buckets merged across workers
        - Single unified metrics response regardless of which worker handles request
    """
    try:
        # Get singleton MetricsCollector instance
        # This instance has reference to the Prometheus registry with all metrics
        collector = MetricsCollector()

        # Generate Prometheus text exposition format
        # MetricsCollector.get_metrics() internally calls:
        #   generate_latest(registry).decode("utf-8")
        # Returns string with all metrics formatted per Prometheus spec
        metrics_text = collector.get_metrics()

        # Log successful metrics exposition for operational visibility
        # Using debug level since this endpoint is called frequently (every 15s)
        logger.debug(
            "Metrics endpoint accessed successfully",
            extra={
                "action": "metrics_endpoint_success",
                "metrics_size_bytes": len(metrics_text),
            },
        )

        # Return metrics with proper Content-Type header per Prometheus spec
        # Content-Type MUST include version and charset for Prometheus compatibility
        # Per Section 6.5.3: text/plain; version=0.0.4; charset=utf-8
        return (
            metrics_text,
            200,
            {"Content-Type": "text/plain; version=0.0.4; charset=utf-8"},
        )

    except Exception as e:
        # Catch all exceptions to prevent endpoint from crashing
        # Graceful degradation: return error without exposing internal details
        error_type = type(e).__name__

        # Log error with structured fields for CloudWatch troubleshooting
        # Include action field for filtering Jira operations in logs
        logger.error(
            f"Failed to generate metrics: {error_type}",
            extra={
                "action": "metrics_endpoint_error",
                "error_type": error_type,
            },
            exc_info=True,  # Include sanitized stack trace for debugging
        )

        # Return 500 Internal Server Error with generic message
        # Never expose exception details to metrics scraper per security requirements
        # Prometheus will mark this scrape as failed and alert if threshold exceeded
        return (
            "Internal server error during metrics generation\n",
            500,
            {"Content-Type": "text/plain; charset=utf-8"},
        )


# Export blueprint for registration in Flask application factory
# Per Section 0.5.1: Blueprint registered in src/app/__init__.py create_app()
__all__ = ["metrics_bp"]
